export const BUSINESS_CONFIG = {
  name: "Liam's Beauty",
  tagline: "Beauty and Style",
  phone: "053-334-3135",
  phoneRaw: "0533343135",
  whatsapp: "972533343135",
  whatsappMessage: "היי ליאם, אשמח לקבוע תור 😊",
  whatsappMessageEn: "Hi Liam, I'd like to book an appointment 😊",
  email: "liams.beauty@gmail.com",
  instagram: "liams.beauty",
  facebook: "liamsbeauty",
  tiktok: "liams.beauty",
  location: {
    city: "אור עקיבא",
    cityEn: "Or Akiva",
    address: "אור עקיבא, מרכז השרון",
    addressEn: "Or Akiva, Sharon Area",
    lat: 32.5031,
    lng: 34.9191,
  },
  hours: {
    he: "ראשון–חמישי: 09:00–20:00 | שישי: 09:00–14:00",
    en: "Sun–Thu: 09:00–20:00 | Fri: 09:00–14:00",
  },
  bookingUrl: process.env.NEXT_PUBLIC_BOOKING_URL || "#contact",
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://liamsbeauty.co.il",
};

export const GALLERY_ITEMS = [
  {
    id: "eb1",
    type: "image" as const,
    src: "/assets/images/eb1.jpeg",
    category: "eyebrows",
    labelHe: "עיצוב גבות",
    labelEn: "Eyebrow Design",
  },
  {
    id: "eb2",
    type: "image" as const,
    src: "/assets/images/eb2.jpeg",
    category: "eyebrows",
    labelHe: "עיצוב גבות — תוצאה",
    labelEn: "Eyebrow Design — Result",
  },
  {
    id: "lb1_after",
    type: "image" as const,
    src: "/assets/images/lb1_after.jpeg",
    category: "hair",
    labelHe: "החלקת שיער — אחרי",
    labelEn: "Hair Straightening — After",
  },
  {
    id: "lb1_before1",
    type: "image" as const,
    src: "/assets/images/lb1_before1.jpeg",
    category: "hair",
    labelHe: "שיער — לפני",
    labelEn: "Hair — Before",
  },
  {
    id: "lb1_before2",
    type: "image" as const,
    src: "/assets/images/lb1_before2.jpeg",
    category: "hair",
    labelHe: "שיער — לפני",
    labelEn: "Hair — Before",
  },
  {
    id: "lb2_after",
    type: "image" as const,
    src: "/assets/images/lb2_after.jpeg",
    category: "hair",
    labelHe: "החלקת שיער — אחרי",
    labelEn: "Hair Straightening — After",
  },
  {
    id: "lb1_video",
    type: "video" as const,
    src: "/assets/videos/lb1_after.mp4",
    poster: "/assets/images/lb1_after.jpeg",
    category: "hair",
    labelHe: "תוצאת החלקה — וידאו",
    labelEn: "Straightening Result — Video",
  },
  {
    id: "lb2_video_after",
    type: "video" as const,
    src: "/assets/videos/lb2_after.mp4",
    poster: "/assets/images/lb2_after.jpeg",
    category: "hair",
    labelHe: "לפני ואחרי — וידאו",
    labelEn: "Before & After — Video",
  },
];
